### ISSUE TITLE
Add tutorial section on credential management

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/concourse-tutorial#101]

**Comment by drnic** [comment]
My current thinking is to make it easy to add credhub/uaa to the `concourse-lite.yml` manifest via an ops file; like in `bucc` project.

**Comment by norman-abramovitz** [comment]
I ran into two issues with the credential management.   First (( variable )) does not work while ((varialbe)) does work (concourse 3.5)   I did not test out ((variable )) or (( variable)) since spruce put in the spaces.

The second issue was getting the credential variables to pass through spruce.   The ((!variable)) syntax is supposed to work, but sometimes it fails.  No consistency, so no way to create an issue that can be acted upon.

**Comment by drnic** [comment]
Section written on `develop` branch and published to https://concoursetutorial.com/basics/15_secret_parameters/
