### ISSUE TITLE
Do you have a tutorial job to dry-run a task and waiting for unblock?

### ISSUE THREAD

**Issue by ozbillwang** [starkandwayne/concourse-tutorial#104]
I need to run several tasks to apply the terraform changes. 

The tasks will be: 

terraform plan ( a `dry-run`)
block (waiting for unblock, y/n)
terraform apply (apply the changes)

So every time, when the resource (git) on branch `master` detects a new commit, it will trigger the job `terraform plan`. Then wait (block). 

I need to read the output from the job `terraform plan` if the configuration changes are fine. Then I can click a button (or input y/n) to unblock the pipeline and allow the next job run `terraform apply`. 

I have the same request to run ansible job with `--check` as dry-run.

For your reference, you can read this document (https://buildkite.com/docs/pipelines/block-step) , it introduces the block function in buildkite

**Comment by drnic** [comment]
Specifically for the terraform request, I'll pass - its a tricky scenario for ppl to follow along with as it requires credentials/accounts with IaaS/clouds.

The scenario of "run a long task and poll something until its finished; and perhaps time out if it doesn't finish before some number of minutes or hours" is interesting. I currently don't have an example from any of my pipelines I can think of to borrow from.

If anyone else has an example and can share it, I'll try to add it as a lesson.
