### ISSUE TITLE
#44 BOSH Stemcells & Releases how do i get the latest version of bosh-stemcell-aws

### ISSUE THREAD

**Issue by MinsuLim** [starkandwayne/concourse-tutorial#107]
hi friends,
I had a problem while getting the latest version of bosh-stemcell-aws.
I excepted 3312.38 latest version but I got 3263.28 version of bosh-aws-xen-ubuntu-trusty-go_agent.

I didn't modify anything in pipeline.yml in 44_bosh_io path. 
resources:
- name: bosh-stemcell-aws
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-ubuntu-trusty-go_agent

Is there a way to get the latest version 3312.38 ?
I'm using fly CLI 3.5.0 version. 
Thank you for helping me in advance.

**Comment by drnic** [comment]
I've decided to remove the bosh lessons for the moment (in develop branch). I might revisit them again later.
