### ISSUE TITLE
no workers satisfying: resource type 'archive'

### ISSUE THREAD

**Issue by rrawat4** [starkandwayne/concourse-tutorial#109]
Hi,

I have installed concourse and fly using the following tutorial on mac:
https://gist.github.com/kevin-smets/f20afd45a24ab3f88d01b2049ce7744f
and had to change the yml file like the following:
`platform: darwin
run:
  path: echo
  args: [hello world]`

which worked, but now I am getting following error with 02_task_inputs 

$ fly --target tutorial execute --config inputs_required.yml --input some-important-input=.
executing build 17
no workers satisfying: resource type 'archive'

available workers: 
  - platform 'darwin'
errored

**Comment by drnic** [comment]
@rrawat4 we're not the maintainers of concourse itself; perhaps visit their slack channel or raise a ticket with the gist's tutorial author?
