### ISSUE TITLE
Vagrant Box Add fails on windows

### ISSUE THREAD

**Issue by kheiligh** [starkandwayne/concourse-tutorial#110]
I've gotten the same problem with Vagrant v. 1.9 and 2.0.1 - running the command

`vagrant box add concourse/lite --box-version $(cat VERSION)`

gives me this message & error:

```
Found VERSION file, using concourse/lite version 3.2.1
==> box: Box file was not detected as metadata. Adding it directly...
You specified a box version constraint with a direct box file
path. Box version constraints only work with boxes from Vagrant
Cloud or a custom box host. Please remove the version constraint
and try again.
```

so I can't get the vagrant box even running.

**Comment by drnic** [comment]
I'm hoping we can move everyone to the `bosh create-env` instructions. They are pretty lovely; and start to introduce you to using BOSH to maintain Concourse later on.

Perhaps you can try installing `bosh` via https://bosh.io/docs/cli-v2.html instructions.

Then try deploying Concourse to Virtualbox using:

```
wget https://raw.githubusercontent.com/starkandwayne/concourse-tutorial/develop/manifests/concourse-lite.yml
bosh create-env manifests/concourse-lite.yml --state tmp/state.json
```

**Comment by choumarin** [comment]
Hi,
Just wanted to point out that `bosh create-env manifests/concourse-lite.yml --state tmp/state.json` doesn't work on Windows, getting the following error:
```
Extracting release '.bosh\downloads\960545597eaba699eed28d96574acd5c2434a40f-361d4ca59030ec1af5f5ad61a31a9c0aa593e819':
  Extracting release:
    Shelling out to tar:
      Running command: 'powershell tar --no-same-owner -xzf .bosh\downloads\960545597eaba699eed28d96574acd5c2434a40f-361d4ca59030ec1af5f5ad61a31a9c0aa593e819 -C .bosh\installations\1adfc68f-2a0a-408f-5756-c89f3f71a6a5\tmp\bosh-release395705526', stdout: '', stderr: '/cygdrive/c/Numerical Innovations/DFM Now V7/bin/tar: .bosh\\installations\001adfc68f-2a0a-408f-5756-c89f3f71a6a5\tmp\bosh-release395705526: Cannot chdir: No such file or directory
/cygdrive/c/Numerical Innovations/DFM Now V7/bin/tar: Error is not recoverable: exiting now
stdout: Broken pipe

gzip: ':
        exit status 1

Exit code 1
```

**Comment by drnic** [comment]
I'm sorry I've moved away from the vagrant up instructions that worked for
windows. I was hoping the `bosh create-env` instructions would work for
Windows but didn't get out my Windows laptop to check. I might continue
pursuing the bosh approach for Windows to drive fixes to bosh-cli + bucc
(which also is not for windows). If I fail, I'll return to the vagrant up;
but I don't have a solution to adding credhub/credentials via vagrant so I
worry we lose the Windows people later on. But I guess that's better than
losing them at the start :)

**Comment by choumarin** [comment]
I found the best way to get started was using docker using the instructions here: https://concourse.ci/docker-repository.html
Of course a little adaptation of the instructions were necessary for windows, but it was very straight-forward.

**Comment by drnic** [comment]
@choumarin do you remember what adaptation of the instructions were required? I'm happy to put something into the tutorial to help Windows people.

**Comment by avoidik** [comment]
@drnic you might find this useful
https://github.com/avoidik/compose_concourse

**Comment by drnic** [comment]
Since https://github.com/starkandwayne/concourse-tutorial/releases/tag/v3.10.0 we're moving towards `docker-compose up` for initial deployment, so I'll close this issue for now.
