### ISSUE TITLE
Can I fork this tutorial and translate to Japanese?

### ISSUE THREAD

**Issue by Fufuhu** [starkandwayne/concourse-tutorial#114]
Hi,

I'm trying to use ConcourseCI in the current project.
However, there're very few project members have knowledge of  ConcourceCI.
So, can I fork this and translate to Japanese?

**Comment by drnic** [comment]
Yes you can. I am lucky I was born in a country that uses English and that this was the default language of all computer things. I am empathetic to non english speakers.

I have started a branch pretty-web to refactor all the tutorials into new folders, delete some of tutorials, and to have a nice web UI for the book. Currently hosted at https://concourse-tutorial.cfapps.io but I’ll sort out a nice domain soon.

I believe we should be able to add multiple languages to the UI and also to the search box. Ooh and some fancy language flags :)

I’ll try to finish the branch & merge to master today.

Nic

________________________________

**Comment by Fufuhu** [comment]
Thanks a lot!
I'll try it.

**Comment by drnic** [comment]
The current refactoring + upgrading of deployment/instructions/tests is in the `develop` branch.

**Comment by drnic** [comment]
I'll close this ticket. Feel free to continue using it for conversations.
