### ISSUE TITLE
bosh create-env manifests/concourse-lite.yml --state tmp/state.json fails, no route to host

### ISSUE THREAD

**Issue by kenk667** [starkandwayne/concourse-tutorial#125]
I run bosh create-env manifests/concourse-lite.yml --state tmp/state.json and at the deploying stage I encounter this error;

```
Deploying:
  Applying the agent state:
    Sending apply spec to agent:
      Sending 'get_task' to the agent:
        Performing request to agent:
          Performing POST request:
            Post https://mbus:<redacted>@192.168.100.4:6868/agent: dial tcp 192.168.100.4:6868: getsockopt: no route to host

Exit code 1
```

I tried manually adding a route to my Ubuntu VM with;

```
route add 192.168.100.0/24 gw 192.168.100.1
```

and I still have the same issue. tried env variable for BOSH _ALL_PROXY, still same issue.

My VM is a Ubuntu 16.04 LTS and is sitting behind a corporate proxy.

**Comment by kenk667** [comment]
just added these routes and trying  again (10.206.91.x is my network);

route add -net 10.206.91.0/24 gw 192.168.100.1
route add -net 192.168.100.0/24 gw 10.206.91.1

**Comment by kenk667** [comment]
output from route:


Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.206.91.1     0.0.0.0         UG    100    0        0 ens192
10.206.91.0     192.168.100.1   255.255.255.0   UG    0      0        0 vboxnet0
10.206.91.0     *               255.255.255.0   U     100    0        0 ens192
link-local      *               255.255.0.0     U     1000   0        0 ens192
192.168.100.0   10.206.91.1     255.255.255.0   UG    0      0        0 ens192
192.168.100.0   192.168.100.1   255.255.255.0   UG    0      0        0 vboxnet0
192.168.100.0   *               255.255.255.0   U     0      0        0 vboxnet0

**Comment by drnic** [comment]
@kenk667 at a glance I'm not sure what `bosh create-env` is doing incorrectly; to get more eyeballs on it I've recreated the issue at https://github.com/cloudfoundry/bosh-cli/issues/387

**Comment by cppforlife** [comment]
it's the routes on the system:

```
192.168.100.0   10.206.91.1     255.255.255.0   UG    0      0        0 ens192
192.168.100.0   192.168.100.1   255.255.255.0   UG    0      0        0 vboxnet0
192.168.100.0   *               255.255.255.0   U     0      0        0 vboxnet0
```

i dont think you should have any of them. if using standard vbox configuration, your machine is 192.168.100.1 and vm would be 192.168.100.4, hence direct comm is allowed.
