### ISSUE TITLE
Tutorial setup fails on Windows

### ISSUE THREAD

**Issue by mjnorman** [starkandwayne/concourse-tutorial#128]
I'm at the point where I am attempting to run "bosh create-env manifests/concourse-lite.yml --state tmp/state.json".   I get the following error.  I can manually extract the installation to the .bosh\installation directory, but can't figure out how to modify the install to realize it's already there.

Extracting release '.bosh\downloads\960545597eaba699eed28d96574acd5c2434a40f-361d4ca59030ec1af5f5ad61a31a9c0aa593e819':
  Extracting release:
    Shelling out to tar:
      Running command: 'powershell tar --no-same-owner -xzf .bosh\downloads\960545597eaba699eed28d96574acd5c2434a40f-361d4ca59030ec1af5f5ad61a31a9c0aa593e819 -C .bosh\installations\8e248f58-d0c7-4ac7-6f2c-a6d864dcc8fa\tmp\bosh-release397827079', stdout: '', stderr: 'tar : The term 'tar' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try again.

**Comment by mahmoodaz** [comment]
From the reference to “powershell” in your output, are you running this on Windows? Which version? Is there a mode of Windows where you get the “tar” command?

________________________________

**Comment by mjnorman** [comment]
Yes Windows 10.  Looks like this is a known bug out there, [here](https://github.com/cloudfoundry/bosh/issues/1821)
I just ended up skipping the first portion and targeting our internal instance of Concourse.  That allowed me to run through all of the tutorials.

**Comment by drnic** [comment]
Yep, every tutorial should run against any concourse. I’ll try to make that clear.

Once you get to the section on Secret Parameters you’ll want a concourse with credhub enabled; or just skip it until you have one. You can always continue with all sections by passing parameters thru the CLI flags.

________________________________
