### ISSUE TITLE
URI in repo description points to old URI

### ISSUE THREAD

**Issue by jchesterpivotal** [starkandwayne/concourse-tutorial#132]
It should now be concourse-ci.org.

**Comment by drnic** [comment]
AFAIK all references to concourse.ci have been changed to concourse-ci.org, thanks to the concourse core team. If you spot any specific changes, it'd be super helpful if you can make a quick PR for the change.

**Comment by jchesterpivotal** [comment]
I would, but I can't open a PR for a Github setting on the repo itself.

[This screenshot might help](https://i.imgur.com/5hnSNbl.png).

**Comment by norman-abramovitz** [comment]
Thanks, @jchesterpivotal! I updated the description now.   Please verify that it is changed now for you.

**Comment by jchesterpivotal** [comment]
All clear! Thankyou.
