### ISSUE TITLE
Tutorial - Pipeline name mistyping

### ISSUE THREAD

**Issue by ecs28** [starkandwayne/concourse-tutorial#149]
Hey guys I found mistyping error following the tutorial steps. I think the correct should be **_helloworld_**, instead of **_hello-world_** on the pipeline unpause instruction.

Cheers.

------------

<img width="750" alt="screen shot 2018-06-18 at 10 31 05" src="https://user-images.githubusercontent.com/31065297/41562680-432af93c-7345-11e8-936e-58c70e74ac49.png">

**Comment by drnic** [comment]
Thanks. We accidentally were using both `helloworld` and `hello-world`. This is gradually getting fixed thanks to reports like this.
