### ISSUE TITLE
Getting started failed

### ISSUE THREAD

**Issue by BrendanBall** [starkandwayne/concourse-tutorial#152]
I was just about to check out concourse, but failed getting past getting started as the docker-compose.yml from https://concourse-ci.org/docker-compose.yml as referenced in the tutorial results in concourse not starting up. Concourse logs:
```
the required flag `--worker-work-dir' was not specified
```

**Comment by drnic** [comment]
Thanks. See #153 for discussion of short term fix.

    wget https://raw.githubusercontent.com/starkandwayne/concourse-tutorial/master/docker-compose.yml
    docker-compose up -d
