### ISSUE TITLE
Outdated docs?

### ISSUE THREAD

**Issue by IgorGee** [starkandwayne/concourse-tutorial#156]
```
➜  task-hello-world git:(master) fly -t execute -c task_hello_world.yml
error: unknown flag `c'
```

**Comment by ahartpence** [comment]
Make sure you're targeting your Concourse before `execute`.

`fly -t bucc execute -c task_hello_world.yml`

<img width="855" alt="screen shot 2018-09-06 at 1 43 55 am" src="https://user-images.githubusercontent.com/13159262/45137445-afe3cf80-b176-11e8-9752-14247e5b501a.png">

**Comment by IgorGee** [comment]
Ah, my apologies.

That's what I get for coding while struggling to keep my eyes open.
