### ISSUE TITLE
all fly -t commands seem broken with 0.54.0

### ISSUE THREAD

**Issue by jbayer** [starkandwayne/concourse-tutorial#16]
with vagrant you don't need to specify, but you may want to consider using the `--target http://192.168.100.4:8080` syntax unless @vito or @xeobus explain what happened.

**Comment by drnic** [comment]
Yeah I think that's a good idea to be explicit all the time.

**Comment by jbayer** [comment]
when i actually got the box to upgrade to 0.54.0, then `-t tutorial` started working again.
