### ISSUE TITLE
concourse 4.2.1 - web login is redirecting to 127.0.0.1

### ISSUE THREAD

**Issue by vaisyarajuraju** [starkandwayne/concourse-tutorial#163]
I am running concourse:4.2.1 version in a ubuntu 18.0.4 Server and I could access the concourse web UI after bringing up the docker-compose however on login, it redirect the the request to 127.0.0.1 instead of the actual ubuntu server IP. Is there any way to fix it by keeping the server IP instead of redirecting to local server IP 127.0.0.1

**Comment by ahartpence** [comment]
Yep, all you need to do is edit the `docker-compose.yml` file in the project root.

There's a flag called `CONCOURSE_EXTERNAL_URL`, just append `=0.0.0.0` to the end of it, and it should now point concourse to your servers internal IP address. 

<img width="682" alt="screen shot 2018-09-25 at 11 40 11 am" src="https://user-images.githubusercontent.com/13159262/46025830-cd41f480-c0b7-11e8-9b20-49791142520d.png">

**Comment by drnic** [comment]
@ahartpence do we need to fix the docker-compose.yml?

**Comment by vaisyarajuraju** [comment]
![image](https://user-images.githubusercontent.com/28572787/46027200-4727ad00-c0bb-11e8-8df6-12885414f3b3.png)
![image](https://user-images.githubusercontent.com/28572787/46027224-54dd3280-c0bb-11e8-92bf-c90b78b7685c.png)
![image](https://user-images.githubusercontent.com/28572787/46027236-5eff3100-c0bb-11e8-89f4-8dc88aa4b274.png)

I followed your instrutction and if you see the first image, I have updated the docker compose external URL to 0.0.0.0 but still it redirecting me to 127.0.0.1.  Though I am using 4.2.1 instead of 3.14.1 as your docker compose file stated.

**Comment by ahartpence** [comment]
Yep, looks like that did break in 4.2.1. My bad for not checking before responding.

Make sure you change `CONCOURSE_EXTERNAL_URL` to be equal to your internal IP (http://INTERNAL_IP:8080)
then add a new line called `CONCOURSE_BIND_IP` and set that to `0.0.0.0`

<img width="1543" alt="screen shot 2018-09-25 at 1 31 23 pm" src="https://user-images.githubusercontent.com/13159262/46031665-822fdd80-c0c7-11e8-8c74-233bbf8b8953.png">

@drnic we shouldn't need to change the `docker-compose.yml` file, because this was a specific use case. Most people should have no issue using concourse on localhost.

**Comment by vaisyarajuraju** [comment]
![image](https://user-images.githubusercontent.com/28572787/46048226-49f3c380-c0f6-11e8-9f21-be9e74747464.png)
![image](https://user-images.githubusercontent.com/28572787/46048254-67289200-c0f6-11e8-91a8-7954e73d6236.png)
I am using Ubuntu Server 18.0.4 and I followed all your instruction but the Concourse GUI does not come up. If I dont populate the external URL, then concourse GUI comes up but on login, it redirect to the 127.0.0.1 IP. May be some more guidence would help or you can refer me the older version of docker-compose which we can use.

**Comment by vaisyarajuraju** [comment]
Thank you so much, its working now.

**Comment by jdhines** [comment]
+1 It looks like it's not picking up the token that was saved in `~/.flyrc`

**Comment by jdhines** [comment]
If I do `fly -t tutorial login -u admin -p admin` first, and then the command currently in the docs: `fly -t tutorial execute -c task_hello_world.yml` then it gets a step further, but then I get a "TLS handshake timeout" when it tries to download the busybox image.
