### ISSUE TITLE
Without docker

### ISSUE THREAD

**Issue by RUSshy** [starkandwayne/concourse-tutorial#166]
Hi

Can you please make tutorial to use without that thing docker ?

All i want is run my dotnet project when new commits appear, nothing else

I even tried docker, but 1st command already 1st error, not good sign..

```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by RUSshy** [comment]
Ubuntu 16.04
docker-compone: 1.8.0

This is a vps box from https://www.scaleway.com/

**Comment by RUSshy** [comment]
ok i got it running i downloaded the docker-compose from the link

But now i can't access this page: http://127.0.0.1:8080/

    Failed to connect to 127.0.0.1 port 8080: Connection refused

And if i try to use fly

```
ci git:(3d_pipeline) fly --target tutorial login --concourse-url http://127.0.0.1:8080 -u admin -p admin
logging in to team 'main'

could not reach the Concourse server called tutorial:

    Get http://127.0.0.1:8080/api/v1/info: dial tcp 127.0.0.1:8080: connect: connection refused

is the targeted Concourse running? better go catch it lol
```

Why is it so over complicated ???

**Comment by drnic** [comment]
Later on in the tutorial we move on to using https://github.com/starkandwayne/bucc/ to run Concourse, with a Credhub secrets storage. Perhaps start there and skip the docker method?

https://concoursetutorial.com/basics/secret-parameters/#redeploy-concourse-with-credhub

**Comment by norman-abramovitz** [comment]
This might actually be a docker compose issue where localhost is not exposed from your docker container.   I am going to close this issue since this is quite old and people are not seeing this error.
