### ISSUE TITLE
concourse api example with curl does not work

### ISSUE THREAD

**Issue by jbayer** [starkandwayne/concourse-tutorial#17]
the example to trigger the build from curl [1] does not work:

```
$ curl http://192.168.100.4:8080/pipelines/main/jobs/job-hello-world/builds -X POST
404 page not found
```

maybe @vito knows why? the concourse api does not seem to be documented on the concourse.ci pages that i could find.

[1] https://github.com/starkandwayne/concourse-tutorial/blob/master/README.md#05---trigger-a-job-via-the-concourse-api

**Comment by gogolok** [comment]
Fixed in 77b1575389b9527b18c9ad322948eefaa43295ec

**Comment by jhunt** [comment]
@jbayer can this be closed then?

**Comment by jbayer** [comment]
sure!
