### ISSUE TITLE
update Vagrantfile to use latest-known working box

### ISSUE THREAD

**Issue by jbayer** [starkandwayne/concourse-tutorial#18]
this is a commented out line [1] that should probably be uncommented and modified to be a specific known-to-work box.

i found certain tutorial examples don't work with 0.54.0 because `fly c -c pipeline.yml` no longer works without naming the pipeline. there are other changes too.

[1] https://github.com/jbayer/concourse-tutorial/blob/master/Vagrantfile#L16

**Comment by xiaods** [comment]
+1

**Comment by drnic** [comment]
There have been a few breaking changes each of the last few releases. Will try to upgrade the tutorial again soon.

**Comment by xiaods** [comment]
thanks @drnic

**Comment by mkb** [comment]
Sorry you had difficulty, folks. We updated Concourse to 2.2.1 and fixed a bunch of compatibility issues in #61 so you should be good. #71 is open now up update to 2.5.0.

If you're still seeing compatibility issues please give a shout and I'll take a look. Thanks!
