### ISSUE TITLE
Interest in accepting new tutorial examples?

### ISSUE THREAD

**Issue by aegershman** [starkandwayne/concourse-tutorial#182]
Would you be interested in PRs for more tutorials?

Background: as an "enterprise internal Concourse advocate(?)", I'm often explaining how to best use Concourse. In order to improve communication efficiency, I'm planning on writing some documentation on how to leverage Concourse

**Comment by norman-abramovitz** [comment]
always an interest.   Please go ahead and PR away!

**Comment by aegershman** [comment]
Great to know, will keep this in mind-- thank you 👍
