### ISSUE TITLE
Fix Target Tutorial Sync

### ISSUE THREAD

**Issue by sarathpyerra** [starkandwayne/concourse-tutorial#211]
fly --target tutorial login --concourse-url http://127.0.0.1:8080 -u admin -p admin
fly --target tutorial sync

When you are trying to sync with tutorial version of Fly use.
Syntax: fly -t ${target_name} sync
fly -t $tutorial sync

**Comment by norman-abramovitz** [comment]
The -t is the short form for --target.   At the place in the tutorial where these commands exist, we are using the long form for options.   Either form will work.   There is an inconsistency within the fly command what gets generated in error messages.   This is not an issue that the tutorial can resolve.
