### ISSUE TITLE
Pipeline Resources

### ISSUE THREAD

**Issue by chutimaNan** [starkandwayne/concourse-tutorial#235]
<img width="1435" alt="Screen Shot 2563-08-28 at 17 43 26" src="https://user-images.githubusercontent.com/52516526/91552497-1c54cc00-e956-11ea-8270-552392c51fa9.png">

I encountered this issue while trying to input resource resource-tutorial feeding into the job job-hello-world.
Currently, I cannot ping github.com but I can use git clone.
Do I need to edit the code in pipeline-resources/pipeline.yml to be able to trigger the job?

I appreciate any help you can provide.

**Comment by norman-abramovitz** [comment]
I am going to close this issue since other related [concourse ](https://github.com/concourse/concourse/issues/7237) issues probably solved this issue as well
