### ISSUE TITLE
fatal : Could not resolve host: github.com

### ISSUE THREAD

**Issue by adampeklay** [starkandwayne/concourse-tutorial#240]
I may have time to look into this, this weekend and get a PR made wherever that may need to happen.

I wanted to report his issue in the interim.

```
check:
resource-tutorial
13:27:27
selected worker: 613ff875e469
13:27:27
Cloning into '/tmp/git-resource-repo-cache'...
13:27:32
fatal: unable to access 'https://github.com/starkandwayne/concourse-tutorial.git/': Could not resolve host: github.com
13:27:32
```

(Docker Desktop v 3.3.3)

**Comment by norman-abramovitz** [comment]
Has this issue cleared up for you?   This seems like either a DNS or Firewall would be the issue here.

**Comment by adampeklay** [comment]
I'm going to revisit this shortly, some context switching had me pivot away from this topic.  I'll post an update relatively soon.

**Comment by adampeklay** [comment]
its working great now, not sure what the problem was but I'm guessing I was connected to a VPN and forgot!
