### ISSUE TITLE
Incorrectly formatted list in the "Getting started" section

### ISSUE THREAD

**Issue by link2xt** [starkandwayne/concourse-tutorial#242]
It is on the front page of https://concoursetutorial.com/ and formatted as a single line:

> Following are the issues could face during windows a) For windows amd issue . please follow below steps. - Right click Docker instance - Go to Settings -> Daemon -> Advanced -> Set the "experimental": true - Restart Docker - Switch to Linux container and restart the docker"

I have commented in the PR adding it: https://github.com/starkandwayne/concourse-tutorial/pull/210#issuecomment-847161107

It's unclear what "windows amd issue" is, whether the issue still exists and how suggested steps resolve it.

**Comment by norman-abramovitz** [comment]
Closing issue since the PR has been deployed
