### ISSUE TITLE
Incorrect syntax in  tutorial 

### ISSUE THREAD

**Issue by joblini** [starkandwayne/concourse-tutorial#253]
There is a syntax error in the Fly Help section of the Introduction to Concourse tutorial.

https://concoursetutorial.com/#fly-help

Using option long forms as in the fly login command above, makes the command line hard to read, so we will use the short option forms in the remainder of this tutorial. Here is the login command again using the short option names.

fly -t tutorial login --c http://127.0.0.1:8080 -u admin -p admin
 
--c should be -c (single dash)

**Comment by norman-abramovitz** [comment]
Thanks!

**Comment by norman-abramovitz** [comment]
done
