### ISSUE TITLE
Website not accessible

### ISSUE THREAD

**Issue by iomarcovalente** [starkandwayne/concourse-tutorial#258]
I get 

```
Error 525 Ray ID: 71fd8c4bfe158885 • 2022-06-23 13:25:09 UTC
SSL handshake failed
```

when accessing the [website](https://concoursetutorial.com/)

![Screenshot 2022-06-23 at 14 25 15](https://user-images.githubusercontent.com/12092106/175310041-815c35f9-4b04-4a33-b624-c5988ff522fe.png)

**Comment by tpoland** [comment]
Hi Marco, thank you for the call out, this has been corrected.
