### ISSUE TITLE
fly save-target does not exist in 0.66.1

### ISSUE THREAD

**Issue by mikegehard** [starkandwayne/concourse-tutorial#28]
Thanks for this tutorial!

You now use fly login to set aliases for targets but when running on a local Virtualbox Concourse setup there isn't any auth set up so running `fly -t tutorial login -c 'http://192.168.100.4:8080/'` is a no-op.

Solutions:
* use the IP:port of the concourse server - this is pretty verbose
* set up auth on the server - this is pretty advanced right out of the gate
* create another Vagrant box with auth set up - could be time consuming to configure.

**Comment by rafaelmagu** [comment]
For the record, creating `~/.flyrc` manually with the below works:
```targets:
  tutorial:
    api: http://192.168.100.4:8080
    username: ""
    password: ""
    cert: ""
```

**Comment by mikegehard** [comment]
Thanks for the heads up!
