### ISSUE TITLE
strange character in the terminal

### ISSUE THREAD

**Issue by HaveF** [starkandwayne/concourse-tutorial#31]
I use git-for-windows(1.9.5), and the shell is based on mingw32. When I run the tutorial, strange character appears like below. Do you have any ideas? thanks!

![sc-2015-11-17_17_27_42](https://cloud.githubusercontent.com/assets/54462/11207564/e539c8a8-8d50-11e5-9286-e8e51964dfd6.png)

Same thing happened, when I use `cmd` of windows:

![sc-2015-11-17_17_33_56](https://cloud.githubusercontent.com/assets/54462/11207649/6429ec2e-8d51-11e5-9044-ca00770cc84f.png)

**Comment by filefrog** [comment]
Those look like ANSI escape sequences for colorized output to me.  Is your `$TERM` variable set properly?

**Comment by HaveF** [comment]
Yes, it is related with ANSI escape sequences. But I suppose it should be fine in one of my shell `mingw32` or `cmd` at least.

**Comment by filefrog** [comment]
What $TERM and encoding are you using?

**Comment by HaveF** [comment]
on the `mingw32` :  `$TERM=cygwin`
on the windows's cmd, no such a variable in the environment
