### ISSUE TITLE
01 - Hello World task(permission problem)

### ISSUE THREAD

**Issue by HaveF** [starkandwayne/concourse-tutorial#32]
when I do this task:
`$ fly -t tutorial execute -c task_show_uname.yml`

![sc-2015-11-17_17_36_42](https://cloud.githubusercontent.com/assets/54462/11207728/cd523a26-8d51-11e5-9b53-0bb853eff1e1.png)
![sc-2015-11-17_17_36_50](https://cloud.githubusercontent.com/assets/54462/11207730/cf7964c8-8d51-11e5-89bb-8e8ad8c522e1.png)

What can I do next?

**Comment by xiaods** [comment]
have a try the new update code base, it works like a charm now.

**Comment by drnic** [comment]
Excellent. Thanks for the update!

On Mon, Feb 29, 2016 at 7:46 PM, Deshi Xiao <notifications@github.com>
wrote:

> have a try the new update code base, it works like a charm now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starkandwayne/concourse-tutorial/issues/32#issuecomment-190127376>
> .
>



-- 
Dr Nic Williams
Stark & Wayne LLC - consultancy for Cloud Foundry users
http://drnicwilliams.com
http://starkandwayne.com
cell +1 (415) 860-2185
twitter @drnic

**Comment by mkb** [comment]
Sounds like this is fixed. @HaveF if you're still having a problem please let us know. Thanks!
