### ISSUE TITLE
always not authorized. run the following to log in

### ISSUE THREAD

**Issue by xiaods** [starkandwayne/concourse-tutorial#38]
```
fly -t tutorial login -c http://10.3.11.17:31868/ -u atc -p atc
```

but i can't login

**Comment by drnic** [comment]
Which chapter/section are you up to?

I'm currently rewriting sections. I'm up to 14.

**Comment by xiaods** [comment]
@drnic i use https://github.com/savaki/concourse-atc to run the concourse instance. i am in section 3.

**Comment by xiaods** [comment]
i guess the concourse-atc's version is very old. i will update the latest version to retry.

**Comment by Aid19801** [comment]
Hi guys, what was the resolution to this? We have a similar issue but on a private network instance of Concourse. Mine works, my colleague's fails with "not authorized. run the following to log in".

When she logs in... fly cannot find the target.

Any ideas?
