### ISSUE TITLE
04 create basic step 4 tutorial.

### ISSUE THREAD

**Issue by xiaods** [starkandwayne/concourse-tutorial#39]
it show long time to perform the "checking pipeline is not paused" step, no error, just take long time to perform

**Comment by xiaods** [comment]
don't know what reason caused the issue.

**Comment by xiaods** [comment]
```
$ cat pipeline.yml 
---
jobs:
- name: job-hello-world
  public: true
  plan:
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: index.alauda.cn/library/busybox
          tag: 'latest'
      run:
        path: echo
        args: [hello world]
```

**Comment by xiaods** [comment]
if i run one task, it quick response the result.

**Comment by xiaods** [comment]
my debug steps:

```
$ fly -t tutorial pipelines
name        paused
helloworld  yes    
```
i found the pipeline is paused default. so i remove the paused flag, the the next job is working.

**Comment by drnic** [comment]
In section 4 https://github.com/starkandwayne/concourse-tutorial#04---basic-pipeline I document that you need to unpause a pipeline after first creating it. Text includes:

As suggested, un-pause a pipeline from the fly CLI:

```
fly -t tutorial unpause-pipeline -p helloworld
```

Is that helpful or how else do you recommend I document this to improve readability?
