### ISSUE TITLE
12 - golang-test-web-app fails to find martini package

### ISSUE THREAD

**Issue by drnic** [starkandwayne/concourse-tutorial#4]
```
golang-test-web-app
main.go:7:2: cannot find package "github.com/go-martini/martini" in any of:
	/usr/src/go/src/github.com/go-martini/martini (from $GOROOT)
	/go/src/github.com/go-martini/martini (from $GOPATH)
```

**Comment by benmoss** [comment]
I forked the go app and created this script which sets the GOPATH to the Godeps directory before running `go test`: https://github.com/benmoss/simple-go-web-app/blob/master/test

That sound reasonable to you?

**Comment by drnic** [comment]
Sounds perfect; thanks! PR away.
