### ISSUE TITLE
Confusing benefit/downside section in tutorial 05

### ISSUE THREAD

**Issue by jondelmil** [starkandwayne/concourse-tutorial#41]
> There is a benefit and a downside to abstracting tasks into YAML files outside of the pipeline.
> 
> One benefit is that the behavior of the task can be kept in sync with the primary input resource (for example, a software project with tasks for running tests, building binaries, etc).
> 
> One downside is that the pipeline.yml no longer explains exactly what commands will be invoked. Comprehension of pipeline behavior is potentially reduced.
> 
> But one benefit of extracting inline tasks into task files is that pipeline.yml files can get long and it can be hard to read and comprehend all the YAML. Instead, give tasks long names so that readers can understand what the purpose and expectation of the task is at a glance.
> 
> But one downside of extracting inline tasks into files is that fly set-pipeline is no longer the only step to updating a pipeline.

At first it says there's "a benefit and a downside" but then lists two of each. Another confusing part is that the second benefit reads like a downside. Am I reading this correctly?

**Comment by mkb** [comment]
Thanks for pointing this out, @jondelmil! I've addressed it in #5fc16ad which will hopefully be merged soon.
