### ISSUE TITLE
The specified host network collides with a non-hostonly network!

### ISSUE THREAD

**Issue by shanFitGit** [starkandwayne/concourse-tutorial#48]
While trying to run the tutorial, I got this error 

The specified host network collides with a non-hostonly network!
This will cause your specified IP to be inaccessible. Please change
the IP or name of your host only network so that it no longer matches that of
a bridged or non-hostonly network.

when I ran the 
`vagrant up`

How can I resolve this issue?

Thanks!

**Comment by jhunt** [comment]
Can you provide more details on your network configuration?
