### ISSUE TITLE
better use long form of the command line parameter

### ISSUE THREAD

**Issue by clfsoft** [starkandwayne/concourse-tutorial#49]
take this for example
set-pipeline --config pipeline.yml --pipeline my-pipeline
instead of 
set-pipeline -c pipeline.yml -p my-pipeline

or you have to check the source to find out the meaning 
(https://github.com/concourse/fly/blob/master/commands/set_pipeline.go)

PS. the document site (https://concourse.ci/fly-cli.html ) use long form.

**Comment by drnic** [comment]
I can appreciate/agree that it's better for people learning to see the long-form of each flag.
