### ISSUE TITLE
11 - Job never executed

### ISSUE THREAD

**Issue by joshuajabbour** [starkandwayne/concourse-tutorial#52]
The directions never say to run the job, and it doesn't start automatically. Not sure if it's necessary, but I spent a few minutes debugging this since all previous jobs have been executed.

**Comment by mkb** [comment]
Good catch. Thanks for letting us know. I've addressed this in starkandwayne/concourse-tutorial#72.

**Comment by mkb** [comment]
Should be fixed now. Please give a shout if you see anything else.
