### ISSUE TITLE
concourse/concourse-ci no longer exists

### ISSUE THREAD

**Issue by vito** [starkandwayne/concourse-tutorial#55]
A few steps of this tutorial depend on `concourse/concourse-ci` - that was never meant to be a publicly used image, as it's only meant for our CI pipeline. It no longer exists - this tutorial should probably refer to a specific image built for the tutorial instead.

**Comment by snarlysodboxer** [comment]
I ran into this issue going through step 12 - Publishing Outputs. I get a 401 unauthorized in the `job-bump-date` job.
Here's the line that uses that image: https://github.com/starkandwayne/concourse-tutorial/blob/master/12_publishing_outputs/bump-timestamp-file.yml#L6

**Comment by drnic** [comment]
I'll try to do another round of fixes to concourse-tutorial soon.

**Comment by sradnidge** [comment]
@snarlysodboxer I'm not sure that's related to this... I'm getting the same err, but using a valid Docker image (which has git)?

**Comment by davidmorley** [comment]
Same issue as @snarlysodboxer. I tried using `busybox` instead of `concourse/concourse-ci`, but with the same results (`401`).

**Comment by snarlysodboxer** [comment]
@sradnidge @davidmorley i was able to get it to work with `repository: concourse/busyboxplus, tag: git` - as suggested by Vito in Concourse CI's Slack channel.

**Comment by sradnidge** [comment]
Ah gotcha - nice one @snarlysodboxer

**Comment by cuevee** [comment]
I'm still getting the same thing even with the image @snarlysodboxer suggested.

**Comment by jhunt** [comment]
I think this may have been fixed in https://github.com/starkandwayne/concourse-tutorial/commit/57567abc2b022c887870529d45b8500ae5869349

@cuevee have you given `concourse/bosh-cli` a shot?

**Comment by mkb** [comment]
Yes, this was addressed in 57567ab.
