### ISSUE TITLE
examples for output passing between plans

### ISSUE THREAD

**Issue by cakester** [starkandwayne/concourse-tutorial#56]
i desperately need to pass output from one plan to another, wonder if that's duable, or any way of passing parameters between plans, im stuck

**Comment by drnic** [comment]
There are two scenarios for passing output:
* between steps to other steps/put resources* between jobs in a pipeline
Which are you looking for some extra help on?






On Tue, Aug 16, 2016 at 10:31 AM +1000, "cakester" <notifications@github.com> wrote:












i desperately need to pass output from one plan to another, wonder if that's duable, or any way of passing parameters between plans, im stuck

**Comment by mkb** [comment]
@cakester : Did either of the approaches @drnic mentioned work for you?

You'll get the quickest response from [the Concourse team on Slack](http://slack.concourse.ci/). You might also try [the Concourse project](https://github.com/concourse/concourse/issues) for issues with Concourse itself as opposed to this tutorial.

**Comment by marco-m** [comment]
Worthwhile closing this issue due to timeout/unrelated with tutorial?

**Comment by mkb** [comment]
@marco-m Yes, I think so.

@cakester We're closing this since it doesn't look related to the tutorial. If you disagree please let us know and we'll take another look. Thanks!
