### ISSUE TITLE
02_task_inputs fails (ubuntu/docker installation)

### ISSUE THREAD

**Issue by ppcuban** [starkandwayne/concourse-tutorial#58]
Hello,

Thanks for this tutorial. I am facing this issue.

Joe@SEVEN64 /c/Concourse/concourse-tutorial/02_task_inputs (master)
$ fly -t tutorial e -c inputs_required.yml -i some-important-input=.
executing build 12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (7) Failed to connect to 192
.168.0.9 port 80: No route to host
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
[31mfailed[0m
upload request failed: Put http://192.168.0.9/api/v1/pipes/0711287c-1dd7-4db7-58a7-8c23fb7b6762: dial tcp 192.16
8.0.9:80: i/o timeout

I have no clue what's going on here. Can you help please?

**Comment by jutkko** [comment]
Hey @ppcuban I had the same issue when I installed concourse this way https://concourse.ci/docker-repository.html, but for concourse-lite things are just fine. How are you running your concourse? 

Also, this doesn't seem to be an issue with this tutorial, more like a concourse problem.

**Comment by mmorejon** [comment]
Hello,

I'm working with Docker (concourse/concourse) and I have the same problem!!

manuels-iMac:02_task_inputs manuel$ fly -t ci execute -c inputs_required.yml -i some-important-input=.
executing build 255
upload request failed: Put /api/v1/pipes/864983b0-705a-4777-6fa7-f5c7c912abe2: unsupported protocol scheme ""
curl: (3) <url> malformed
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
failed

Any suggestion???

**Comment by jutkko** [comment]
@mmorejon I don't think it is this tutorial's problem. I used concourse-lite and things are working fine. For concourse issues, please have a look at their slack channel https://concourse.slack.com/.

**Comment by mkb** [comment]
@ppcuban @mmorejon : What do you see when you type `fly -t tutorial pipelines`?

If you're running Concourse differently than the tutorial steps you'll need to make sure your Concourse is in working order and that `fly` can talk to it.

**Comment by NaurisSadovskis** [comment]
It seems that API call is being made to port 80, while the server is running on (default) 8080. Looks like a Concourse issue.

**Comment by NaurisSadovskis** [comment]
Okay, so this issue is due to starting the web service on the wrong port. 

```
concourse web \
  --basic-auth-username myuser \
  --basic-auth-password mypass \
  --session-signing-key session_signing_key \
  --tsa-host-key tsa_host_key \
  --tsa-authorized-keys authorized_worker_keys \
  --external-url http://my-ci.example.com
```

If your web service is running on it's default port (8080), you must set `--external-url` to be `http://my-ci.example.com:8080`

This has solved the issue for me.

**Comment by vguntupalli** [comment]
Thanks @NaurisSadovskis .. above solution has resolved my issue. i.e.,
1. --external-url to be http://my-ci.example.com:8080
2.  stopping & starting web service

**Comment by xanderrman** [comment]
@mmorejon @ppcuban just checking in to see if you'd like me to close the issue, or if this is still a problem 👍

**Comment by ppcuban** [comment]
I solved this problem. It's ok with me if you want to close it.

**Comment by xanderrman** [comment]
great thank you @ppcuban
