### ISSUE TITLE
05 - The gif is out of date

### ISSUE THREAD

**Issue by jutkko** [starkandwayne/concourse-tutorial#60]
There is one step missing from the three-step description below the gif animation, not big deal, but I guess it is not too hard to change that. :)

**Comment by drnic** [comment]
I want to acknowledge I've seen the animation, yep its no longer matching the new UI. There are a few of them. I *might* redo the animated gifs. LICEcap is a nice little app. But for the moment I'll leave them as is as non-critical issue. One day they might really annoy me and I'll redo them :)
