### ISSUE TITLE
Can't find and start virtual box.

### ISSUE THREAD

**Issue by redwyer** [starkandwayne/concourse-tutorial#66]
I can't seem to get started... I don't understand where to look for the box.  I thought it would be pulled down by clone this git repository.
Can anybody interpret for me?
Rex

$ vagrant box add concourse/lite --box-version 2.2.1
Found VERSION file, using concourse/lite version 2.2.1
The box 'concourse/lite' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/concourse/lite"]
Error:

**Comment by 7hunderbird** [comment]
@redwyer can you try removing the [embedded vagrant curl](http://stackoverflow.com/questions/35519389/vagrant-cannot-find-box).  I tried it after being able to reproduce your problem and it worked for me.  I'm hoping it can work for you you too.

**Comment by redwyer** [comment]
Thank you!  I got there another roundabout way that involved rebuilding fly from source.

**Comment by 7hunderbird** [comment]
Sounds great!  Glad to hear you were able to get started.  Ping if you get other questions.

**Comment by sshrivastava-incontact** [comment]
I am facing same issue, but I am using windows environment so not sure if I can try

 $ sudo rm /opt/vagrant/embedded/bin/curl

When I run the command through the bash I get the following error : 

> _$ vagrant box add concourse/lite --box-version $(cat VERSION)
> Found VERSION file, using concourse/lite version 2.7.0
> The box 'concourse/lite' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Atlas, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> 
> URL: ["https://atlas.hashicorp.com/concourse/lite"]
> Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received_


When I run the command through the windows command prompt, then I get the following error

_

> >vagrant box add concourse/lite --box-version $(cat VERSION)
> Found VERSION file, using concourse/lite version 2.7.0
> ==> box: Box file was not detected as metadata. Adding it directly...
> You specified a box version constraint with a direct box file
> path. Box version constraints only work with boxes from Vagrant
> Cloud or a custom box host. Please remove the version constraint
> and try again.

_
