### ISSUE TITLE
Human intervention

### ISSUE THREAD

**Issue by ronaldvanderrest** [starkandwayne/concourse-tutorial#67]
Is there any way to include human intervention in alle pipeline, e.g. for approvals before deploying etc?

**Comment by drnic** [comment]
Only human intervention is to remove triggers from a job, so that only a human or API call can trigger a job, afaik.

**Comment by norman-abramovitz** [comment]
As part of this human interaction, you can also use the email resource to send a message before going into the job that has triggers turned off.
https://github.com/pivotal-cf/email-resource.   The are other resources for other types of messaging system such as SLACK https://github.com/cloudfoundry-community/slack-notification-resource.

**Comment by mkb** [comment]
More generally, if a manual trigger is not sufficient for your purposes, you can [create a custom resource](https://concourse.ci/implementing-resources.html) to request and receive approval from whatever change control tool your org uses.

I'm closing this out as we've hopefully answered your question. A better place for general questions about Concourse (as opposed to this tutorial about it) is the [Concourse team on Slack](http://slack.concourse.ci/) or GitHub issues for the [Concourse project itself](https://github.com/concourse/concourse/issues).

Good luck!
