### ISSUE TITLE
Git tag with concourse version

### ISSUE THREAD

**Issue by johnlonganecker** [starkandwayne/concourse-tutorial#90]
It might be a little hard to accomplish this, but I think it would be really useful every time we do a through pass on the concourse-tutorial we create a git tag that matches concourse's version.

That way anyone following the tutorial will have an idea what version of concourse to use.

**Comment by norman-abramovitz** [comment]
I am might be wrong here, but I thought the VERSION file indirectly tracked the concourse release.   The concourse boshlite environment version is named after the concourse version.

**Comment by drnic** [comment]
In the `develop` branch is a full `manifests/concourse-lite.yml` with precompiled releases. This will ultimately be updated automatically via CI into `develop` branch; and if tests pass then can be merged into stable `master` branch.

Give the new instructions a whirl and let me know if you like them: https://concoursetutorial.com/#mac-linux
