### ISSUE TITLE
docker image is not pulled in helm chart

### ISSUE THREAD

**Issue by thaniyarasu** [starkandwayne/concourse-tutorial#92]
i installed concourse/stable in kubernetes cluster using helm charts.

when i try hello-world
i get this error

annoy
resource script '/opt/resource/check []' failed: exit status 1
stderr:
failed to ping registry: 2 error(s) occurred:

* ping https: Get https://registry-1.docker.io/v2/: dial tcp 184.168.221.96:443: i/o timeout
* ping http: Get http://registry-1.docker.io/v2/: dial tcp 184.168.221.96:80: i/o timeout

**Comment by drnic** [comment]
Perhaps discuss your installation with the concourse core team on their slack channel; 
Once you've got a working concourse then this tutorial will be super useful for learning to use it.

**Comment by thaniyarasu** [comment]
https://github.com/concourse/concourse/issues/937
