### ISSUE TITLE
Storage Driver AUFS vs Overlay2

### ISSUE THREAD

**Issue by jeffsteed** [starkandwayne/concourse-tutorial#97]
Thanks for the tutorial!
Unfortunately, I am running into a technical issue on the first exercise. I am trying to run through your tutorial using docker to run concourse and not virtualbox/vagrant. The problem I am encountering is that (after getting concourse running using the concourse/concourse docker-compose.yml) when I try to run the very first task from the tutorial (task_hello_world.yml), it fails because it is trying to use the aufs storage driver as opposed to the default "Docker for Mac" storage driver, overlay2. 
Is there a way to fix this without forcing my Docker daemon to use aufs as the storage driver? All other images I've ran use overlay2, so I'd like to stick with it, if possible.
```
 fly -t tutorial execute -c task_hello_world.yml 
executing build 1
initializing
Pulling busybox@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f...
sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f: Pulling from library/busybox
7520415ce762: Pulling fs layer
7520415ce762: Verifying Checksum
7520415ce762: Download complete
7520415ce762: Pull complete
Digest: sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f
Status: Downloaded newer image for busybox@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f

Successfully pulled busybox@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f.

docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/66174d331c8ee6e48312a93b9bfe8912031752c38b5e4d292383046c59c18493-init: invalid argument.
See 'docker run --help'.
resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 125
errored
```

**Comment by drnic** [comment]
Sorry for not replying earlier. Hopefully you also raised this issue with the Concourse Core team and got some help.
